Register rules_magic toolchains in bootcamp module
Fixes the previous error, but the build now fails with:

```txt
ERROR: no such package '@@+_repo_rules+rules_magic//external':
  BUILD file not found in directory 'external' of external repository
  @@+_repo_rules+rules_magic. Add a BUILD file to a directory to mark it
  as a package.

ERROR: external/+_repo_rules+rules_magic/magic/BUILD:38:22:
  no such package '@@+_repo_rules+rules_magic//external':
  BUILD file not found in directory 'external' of external repository
  @@+_repo_rules+rules_magic. Add a BUILD file to a directory to mark it
  as a package. and referenced by
  '@@+_repo_rules+rules_magic//toolchains:default_settings_toolchain_impl'

ERROR: Analysis of target '//:default-values' failed; build aborted:
  Analysis failed
```

It is surprising that the `magic_toolchains` extension didn't produce an
error due to `native.register_toolchains`. This is likely because the
build uses no repos from the extension, hence Bazel doesn't evaluate it.