Bump to rules_java 8.6.0
Resolves the previous error under Bazel 8, but Bazel 8 now produces:

```txt
ERROR: external/com_google_protobuf/bazel/private/native.bzl:3:19:
  name 'ProtoInfo' is not defined (did you mean 'proto'?)

ERROR: Error computing the main repository mapping:
  at external/rules_java/java/repositories.bzl:20:6:
  at external/rules_java/toolchains/local_java_repository.bzl:17:6:
  at external/rules_java/java/toolchains/java_runtime.bzl:16:6:
  at external/compatibility_proxy/proxy.bzl:6:6:
  at external/rules_java/java/bazel/rules/bazel_java_test.bzl:20:6:
  at external/rules_java/java/bazel/rules/bazel_java_binary.bzl:26:6:
  at external/rules_java/java/common/rules/impl/java_binary_impl.bzl:17:6:
  at external/com_google_protobuf/bazel/common/proto_info.bzl:3:6:
compilation of module 'bazel/private/native.bzl' failed
```

Bazel 6.5.0 and 7.6.1 now produce the following error (though Bazel 7 fails on
@@com_frobozz_rules_magic//src/com/frobozz/magic:EmitDigestsWorker):

```txt
ERROR: bzlmod-bootcamp/bootcamp/BUILD:7:17:
  While resolving toolchains for target //:default-values:
  invalid registered toolchain '//toolchains:all':
  while parsing '//toolchains:all':
  error loading package '@rules_java//toolchains':
  cannot load '@rules_cc//cc:cc_library.bzl': no such file
```