Bump protobuf from v21.7 to v27.2, add tools/bazel
This is the minimum version required by the `bazel-worker-api` repo
(though we won't add it until we get to Bazel 9 compatibility). Requires
either setting C++ compiler flags or an older `com_google_abseil`
version when building with Bazel 6.

Added the `tools/bazel` Bazelisk wrapper to facilitate Bazel 6 legacy
`WORKSPACE` builds, since these now require different Bazel flags. Also
supports using a custom Bazel 6 binary via `BAZEL_6_BINARY`. For details
on why building a custom Bazel 6 binary is necessary on macOS 26.0
Tahoe, and how to build one, see:

- https://github.com/bazelbuild/bazel/issues/27026

The custom binary resolves the `missing LC_UUID load command` error from
Bazel 6 builds described in the previous commit. Bazel 6 macOS builds
now fail in the same way as Bazel 7 builds, due to the Zlib 1.2.13 +
Xcode 16.4 `OS_CODE` error.

Added `-std=c++17` flags in the new `.bazelrc-cxxopts` with an extensive
comment explaining why they're necessary for some builds and not others.
Added a commented out entry for `abseil-cpp-20220623.1` (a.k.a.
`com_google_abseil`) in `deps.bzl`.

WINDOWS USERS: At this point, create a `C:/b` folder and add a
"$HOME/.bazelrc" containing `startup --output_user_root=C:/b`. With
`protobuf` v27, MSVC starts failing on long path limits:

```txt
ERROR: C:/.../external/com_google_protobuf/src/google/protobuf/compiler/objectivec/BUILD.bazel:44:11:
Compiling src/google/protobuf/compiler/objectivec/line_consumer.cc
  [for tool] failed: (Exit 2): cl.exe failed:
  error executing CppCompile command (from target
    @@com_google_protobuf//src/google/protobuf/compiler/objectivec:line_consumer)

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\HostX64\arm64\cl.exe
... (remaining 1 argument skipped)
external/com_google_protobuf/src/google/protobuf/compiler/objectivec/line_consumer.cc(20):
fatal error C1083: Cannot open include file:
  'google/protobuf/compiler/objectivec/line_consumer.h':
  No such file or directory
```

By `protobuf` v33, this restriction no longer applies.