Replace @bazel_tools with @bazel_worker_api
Replaces `@bazel_tools//src/main/protobuf:worker_protocol_java_proto`
with a dependency on `@bazel_worker_api//:worker_protocol_proto`. This
works with Bazel 7 as well as the `last_green` Bazel.

For the reason behind this, see:

- https://github.com/bazelbuild/bazel/issues/26579#issuecomment-3120862995

Notice the `strip_prefix` trick to make the repo available under legacy
`WORKSPACE` builds. Legacy `WORKSPACE` builds continue to pass under
Bazel 6, 7, and 8.

Note that upgrading `protobuf` to at least v32 will break Bazel 6 legacy
`WORKSPACE` builds:

- https://github.com/protocolbuffers/protobuf/blob/v32.0/bazel/proto_library.bzl#L14-L16

---

Using `bazel_dep(name = "protobuf", ...)` without `repo_name =
"com_google_protobuf"` breaks compatibility with legacy `WORKSPACE`
builds. Bazel will silently use a different `com_google_protobuf`
version for its `@bazel_tools` repo. Bazel 6 and 7 builds will complete,
but Bazel 8 builds will fail.

Importing it as `protobuf` without a `repo_mapping` from
`com_google_protobuf` for other `deps.bzl` dependencies fails with:

```txt
ERROR: external/rules_magic/src/com/frobozz/magic/BUILD:13:19:
  in deps attribute of java_proto_library rule
  @@rules_magic//src/com/frobozz/magic:worker_protocol_java_proto:
  '@@bazel_worker_api//:worker_protocol_proto' does not have mandatory
  providers: 'ProtoInfo'.

  Since this rule was created by the macro 'java_proto_library', the
  error might have been caused by the macro implementation

ERROR: external/rules_magic/src/com/frobozz/magic/BUILD:13:19:
  Analysis of target
  '@@rules_magic//src/com/frobozz/magic:worker_protocol_java_proto'
  (config: d881af7) failed

ERROR: Analysis of target '//:hello' failed; build aborted:
  Analysis failed
```

With the `repo_mapping` for all the other dependencies, it fails with:

```txt
ERROR: external/bazel_worker_api/BUILD.bazel:5:14: in
  @@protobuf//bazel/private:bazel_java_proto_library_rule.bzl%bazel_java_proto_aspect
  aspect on proto_library rule
  @@bazel_worker_api//:worker_protocol_proto:

Traceback (most recent call last):
  File "external/protobuf/bazel/private/bazel_java_proto_library_rule.bzl",
    line 40, column 53, in _bazel_java_proto_aspect_impl
      proto_toolchain_info = toolchains.find_toolchain(ctx, "_aspect_java_proto_toolchain", _JAVA_PROTO_TOOLCHAIN)
  File "external/protobuf/bazel/private/toolchain_helpers.bzl",
    line 29, column 46, in _find_toolchain
      return getattr(ctx.attr, legacy_attr)[ProtoLangToolchainInfo]

Error: <target @@com_google_protobuf//java/core:toolchain>
  (rule 'proto_lang_toolchain') doesn't contain declared provider
  'ProtoLangToolchainInfo'

ERROR: Analysis of target '@@bazel_worker_api//:worker_protocol_proto'
  (config: d881af7) failed

ERROR: Analysis of target '//:hello' failed; build aborted:
  Analysis failed
```