Replace //external target with repo reference
Fixes the breakage from the previous commit and eliminates the now
unnecessary `native.bind()` call.

The Bzlmod build now fails with the following under Bazel 8:

```txt
ERROR: .../external/rules_magic+/magic/magic.bzl:63:31:
  Traceback (most recent call last):
  File ".../external/rules_magic+/magic/extensions/toolchains.bzl",
    line 20, column 27, in _magic_toolchains_impl
      rules_magic_toolchains()
  File ".../external/rules_magic+/magic/magic.bzl",
    line 63, column 31, in rules_magic_toolchains
      native.register_toolchains("//magic:all")

Error in register_toolchains: register_toolchains() can only be used
  while evaluating a WORKSPACE file

ERROR: Analysis of target '//:default-values' failed; build aborted:
  error evaluating module extension
  @@rules_magic+//magic/extensions:toolchains.bzl%magic_toolchains
```

Under Bazel 7, the `ERROR:` lines are identical, but the "Error in
register toolchains:" line reads:

```txt
Error in register_toolchains: The native module can be accessed only
  from a BUILD thread. Wrap the function in a macro and call it from a
  BUILD file
```

This is because `register_toolchains()` can only appear in
`MODULE.bazel` under Bzlmod. `native.register_toolchains()` in a `.bzl`
file is only valid in a legacy `WORKSPACE` context.