Bump to rules_python 1.0.0
Without at least `rules_cc` 0.0.14, building with `rules_python` 1.0.0
fails with:

```txt
ERROR: Traceback (most recent call last):
  File "external/remote_java_tools/BUILD", line 7, column 60, in <toplevel>
    load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_proto_library")
Error: file '@rules_cc//cc:defs.bzl' does not contain symbol 'cc_proto_library'
```