Bump .bazelversion to 8.4.2
The Bazel 6 and 7 builds remain intact, but the Bazel 8 build fails
with:

```txt
ERROR: Traceback (most recent call last):
  File "external/rules_java/java/defs.bzl", line 46, column 28, in <toplevel>
    java_proto_library = native.java_proto_library
Error: no native function or rule 'java_proto_library'

Available attributes: action_listener, [...snip...], xcode_version

ERROR: Error computing the main repository mapping:
  at external/rules_java/java/repositories.bzl:20:6:
  at external/rules_java/toolchains/local_java_repository.bzl:17:6:
  initialization of module 'java/defs.bzl' failed
```

This is because Bazel 8 removes its builtin `*_proto_library` rules.

- bazelbuild/bazel#24215: [8.0.0] Remove Proto rules
  bazelbuild/bazel@f25551b1c54fdcc2b52929a79eb194bda61a030d
  bazelbuild/bazel@86c8b0ff16e91775b0d42107cc4753f4f21d54fb