Fix `magic_toolchains` module extension
The `magic_toolchains` module extension now invokes
`setup_magic_spells_repositories()` directly, instead of
`rules_magic_toolchains()`. This avoids the error described in the
previous commit due to `rules_magic_toolchains()` calling
`native.register_toolchains()` in a module extension context. (Also note
that the `rules_magic/MODULE.bazel` file already invokes
`register_toolchains()`.)

The original toolchains macros still work with legacy `WORKSPACE` builds
in Bazel 6, 7, and 8.

The build now breaks with a similar error to that described in
"Enable Bzlmod, keep legacy WORKSPACE support":

```txt
ERROR: .../external/rules_magic++magic_toolchains+rules_magic_spells_enchanter/BUILD:
  no such target
  '@@rules_magic++magic_toolchains+rules_magic_spells_enchanter//:rules_magic_spells_enchanter':
  target 'rules_magic_spells_enchanter'
  not declared in package '' defined by
  .../external/rules_magic++magic_toolchains+rules_magic_spells_enchanter/BUILD

ERROR: .../external/rules_magic+/magic/BUILD:38:22:
  no such target
  '@@rules_magic++magic_toolchains+rules_magic_spells_enchanter//:rules_magic_spells_enchanter':
  target 'rules_magic_spells_enchanter'
  not declared in package '' defined by
  .../external/rules_magic++magic_toolchains+rules_magic_spells_enchanter/BUILD
  and referenced by
  '@@rules_magic+//magic:default_settings_toolchain_impl'

ERROR: Analysis of target '//:default-values' failed; build aborted:
  Analysis failed
```

Like the previous error, this is due to `repository_ctx.name` now using
the canonical repo name format and breaking a repo's default target.