Explicitly import rules_cc 0.0.14
Resolves the Bazel 6 and 7 breakages. Bazel 8 continues to fail as
before.

---

This is the earliest version that works with `rules_java` 8.5.0 and
Bazel 6.5.0. Versions between 0.0.10 and 0.0.13 produce:

```txt
ERROR: external/rules_cc/cc/private/rules_impl/native.bzl:40:33:
  name 'CcSharedLibraryHintInfo' is not defined
  (did you mean 'CcSharedLibraryInfo'?)

ERROR: external/com_frobozz_rules_magic/src/com/frobozz/magic/BUILD:4:12:
  Target '@com_frobozz_rules_magic//src/com/frobozz/magic:EmitDigestsWorker'
  depends on toolchain '@local_config_cc//:cc-compiler-darwin_arm64',
  which cannot be found: error loading package '@local_config_cc//':
  at external/rules_cc/cc/defs.bzl:25:6:
  at external/rules_cc/cc/common/debug_package_info.bzl:16:6:
  compilation of module 'cc/private/rules_impl/native.bzl' failed'
```

Version 0.0.13 produces the following (which a `repo_mapping` could fix,
but why bother):

```txt
ERROR: external/com_frobozz_rules_magic/src/com/frobozz/magic/BUILD:4:12:
  Target '@com_frobozz_rules_magic//src/com/frobozz/magic:EmitDigestsWorker'
  depends on toolchain '@local_config_cc//:cc-compiler-darwin_arm64',
  which cannot be found: error loading package '@local_config_cc//':
  at external/rules_cc/cc/defs.bzl:16:6:
  Unable to find package for @protobuf//bazel:cc_proto_library.bzl:
  The repository '@protobuf' could not be resolved:
  Repository '@protobuf' is not defined.'
```