Use rules_magic_spells_* repos from toolchain ext
This solves the previous problem, as well as a related problem with the
tests using `spellbreaker_toolchain`.

Now the build breaks due to invoking `new_local_repository` outside of
`MODULE.bazel`:

```txt
ERROR: external/+_repo_rules+rules_magic/toolchains/repositories.bzl:20:36:
  Traceback (most recent call last):
    File "bootcamp/extensions/rules_magic_toolchains.bzl",
      line 6, column 27, in _magic_toolchains_impl
        rules_magic_toolchains()
    File "external/+_repo_rules+rules_magic/magic/magic.bzl",
      line 31, column 37, in rules_magic_toolchains
        _rules_magic_spells_repositories()
    File "external/+_repo_rules+rules_magic/toolchains/repositories.bzl",
      line 20, column 36, in rules_magic_spells_repositories
        native.new_local_repository(

Error in new_local_repository: repository rules can only be used while
  evaluating a WORKSPACE file

ERROR: Analysis of target '//:default-values' failed; build aborted:
  error evaluating module extension
  @@//extensions:rules_magic_toolchains.bzl%magic_toolchains
```