Update Bazel to 9.0.0-pre.20250916.1
This the latest `rolling` release as of 2025-09-30. The build first
breaks with:

```txt
ERROR: Traceback (most recent call last):
  File "external/rules_magic+/magic/magic_library.bzl",
    line 7, column 33, in <toplevel>
      providers = [java_common.JavaToolchainInfo],

Error: 'struct' value has no field or method 'JavaToolchainInfo'
Available attributes: internal_DO_NOT_USE

ERROR: Analysis of target '//:leaflet' failed; build aborted:
  Error loading '@@rules_magic+//magic/extensions:leaflet_repo.bzl'
  for module extensions, requested by bootcamp/MODULE.bazel:9:30:

  at external/rules_magic+/magic/extensions/leaflet_repo.bzl:3:6:
  at external/rules_magic+/magic/magic.bzl:4:6:
  initialization of module 'magic/magic_library.bzl' failed:

  at external/rules_magic+/magic/extensions/leaflet_repo.bzl:3:6:
  at external/rules_magic+/magic/magic.bzl:4:6:
  initialization of module 'magic/magic_library.bzl' failed
```