Emit module name into leaflet_repo extension
Breaks the dependency on the module name, so that the extension will
work no matter the name of the module. Resolves the breakage in the
`@com_frobozz_rules_magic_leaflet` from the previous commit.

Now we're left with the following breakage, whereby an internal target
used to instantiate a repository rule is broken. This is because the
`repo_mapping` attribute applied to the `http_archive` does not transfer
to other repository rules:

```txt
INFO: Repository com_frobozz_rules_magic_spells_enchanter
  instantiated at:
  bootcamp/WORKSPACE:74:23:
    in <toplevel>
  .../external/rules_magic/magic/magic.bzl:77:36:
    in rules_magic_toolchains
  .../external/rules_magic/magic/private/setup_magic_spells_repositories.bzl:38:32:
    in setup_magic_spells_repositories

Repository rule magic_spells_repository defined at:
  .../external/rules_magic/magic/magic_spells_repository.bzl:38:42:
    in <toplevel>

ERROR: An error occurred during the fetch of repository
  'com_frobozz_rules_magic_spells_enchanter':
  Traceback (most recent call last):
  File ".../external/rules_magic/magic/magic_spells_repository.bzl",
    line 34, column 18, in _magic_spells_repository_impl
      rctx.path(rctx.attr.spells_json),

Error in path: Unable to load package for
  @com_frobozz_rules_magic//magic:private/spells/enchanter.json:
  The repository '@com_frobozz_rules_magic' could not be resolved:
  Repository '@com_frobozz_rules_magic' is not defined

ERROR: bootcamp/WORKSPACE:74:23:
  fetching magic_spells_repository rule
  //external:com_frobozz_rules_magic_spells_enchanter:
  Traceback (most recent call last):
  File ".../external/rules_magic/magic/magic_spells_repository.bzl",
    line 34, column 18, in _magic_spells_repository_impl
      rctx.path(rctx.attr.spells_json),

Error in path: Unable to load package for
  @com_frobozz_rules_magic//magic:private/spells/enchanter.json:
  The repository '@com_frobozz_rules_magic' could not be resolved:
  Repository '@com_frobozz_rules_magic' is not defined

ERROR: bootcamp/WORKSPACE:74:23:
  //external:enchanter_spells depends on
  @com_frobozz_rules_magic_spells_enchanter//:com_frobozz_rules_magic_spells_enchanter
  in repository @com_frobozz_rules_magic_spells_enchanter
  which failed to fetch.
  no such package '@com_frobozz_rules_magic_spells_enchanter//':
  Unable to load package for
  @com_frobozz_rules_magic//magic:private/spells/enchanter.json:
  The repository '@com_frobozz_rules_magic' could not be resolved:
  Repository '@com_frobozz_rules_magic' is not defined

ERROR: Analysis of target '//:hello' failed; build aborted:
```