Bump to protobuf v29.0, bazel_skylib 1.7.0
`bazel build //...` now works for Bazel 6.5.0, 7.5.1, and Bazel 8.
`bazel test //...` now works for Bazel 6.5.0 and 7.5.1.

`//:example_test` now fails under Bazel 8 because the runfiles
location changed per bazelbuild/bazel#25198:

```txt
$ bazel test --test_output=all //...

INFO: Analyzed 5 targets (0 packages loaded, 0 targets configured).
FAIL: //:example_test (Exit 127)
  (see execroot/bzlmod_bootcamp/bazel-out/darwin_arm64-fastbuild/testlogs/example_test/test.log)

INFO: From Testing //:example_test:
==================== Test output for //:example_test:
execroot/bzlmod_bootcamp/bazel-out/darwin_arm64-fastbuild/bin/example_test.runfiles/bzlmod_bootcamp/example_test:
  line 11: external/com_frobozz_rules_magic/test/test_framework.sh:
    No such file or directory
execroot/bzlmod_bootcamp/bazel-out/darwin_arm64-fastbuild/bin/example_test.runfiles/bzlmod_bootcamp/example_test:
  line 12: run_test_files:
    command not found
================================================================================
INFO: Found 4 targets and 1 test target...
INFO: Elapsed time: 0.191s, Critical Path: 0.10s
INFO: 2 processes: 4 action cache hit, 2 darwin-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
//:example_test                                                          FAILED in 0.1s
  execroot/bzlmod_bootcamp/bazel-out/darwin_arm64-fastbuild/testlogs/example_test/test.log

Executed 1 out of 1 test: 1 fails locally.
```

This is because the value of `--legacy_external_runfiles` flipped from
`true` in Bazel 7 to `false` in Bazel 8. Building and testing using
`--nolegacy_external_runfiles` with Bazel 7 also fails, and using
`--legacy_external_runfiles` with Bazel 8 passes.

---

Without `bazel_skylib` 1.7.0, Bazel 7 and 8 produce the following error,
indicating that `rules_java` 8.6.0 deps include an older `bazel_skylib`.
Bazel 6 passes, however, probably because it's still using a builtin
`proto_library` rule:

```txt
ERROR: external/com_google_protobuf/src/google/protobuf/BUILD.bazel:130:14:
  in proto_library rule @@com_google_protobuf//src/google/protobuf:wrappers_proto:
Traceback (most recent call last):
  File "external/com_google_protobuf/bazel/private/bazel_proto_library_rule.bzl",
    line 67, column 39, in _proto_library_impl
      import_prefix = _get_import_prefix(ctx)
  File "external/com_google_protobuf/bazel/private/bazel_proto_library_rule.bzl",
    line 39, column 17, in _get_import_prefix
      if not paths.is_normalized(import_prefix):
Error: 'struct' value has no field or method 'is_normalized'
Available attributes: basename, dirname, is_absolute, join, normalize,
  relativize, replace_extension, split_extension

ERROR: external/com_google_protobuf/src/google/protobuf/BUILD.bazel:130:14:
  Analysis of target '@@com_google_protobuf//src/google/protobuf:wrappers_proto' failed
  Target //:default-values failed to build
```