Add bazel_features 1.10.0 to deps.bzl
This fixes the `@bazel_features` error from the previous commit.

Now the Bazel 8 build fails with the following error (the same error
produced by the Bazel 7 build on the previous commit):

```txt
ERROR: external/com_google_protobuf/src/google/protobuf/BUILD.bazel:130:14:
  in proto_library rule
  @@com_google_protobuf//src/google/protobuf:wrappers_proto:
Traceback (most recent call last):
  File "external/com_google_protobuf/bazel/private/bazel_proto_library_rule.bzl",
    line 67, column 39, in _proto_library_impl
      import_prefix = _get_import_prefix(ctx)
  File "external/com_google_protobuf/bazel/private/bazel_proto_library_rule.bzl",
    line 39, column 17, in _get_import_prefix
      if not paths.is_normalized(import_prefix):
Error: 'struct' value has no field or method 'is_normalized'
Available attributes: basename, dirname, is_absolute, join, normalize,
  relativize, replace_extension, split_extension

ERROR: external/com_google_protobuf/src/google/protobuf/BUILD.bazel:130:14:
  Analysis of target
  '@@com_google_protobuf//src/google/protobuf:wrappers_proto' failed
  Target //:default-values failed to build
```

This happens because `protobuf` v29 needs `bazel_skylib` 1.7.0 to define
`paths.is_normalized`. However, the legacy `WORKSPACE` file currently
invokes `py_repositories`, which instantiates `bazel_skylib` 1.3.0,
before `protobuf_deps`. Bazel 6 builds still pass, however, because it's
still using a builtin `proto_library` rule.

- https://github.com/bazel-contrib/rules_python/blob/0.37.2/python/private/py_repositories.bzl#L48-L55
- https://github.com/bazelbuild/bazel-skylib/blob/1.3.0/lib/paths.bzl
- https://github.com/bazelbuild/bazel-skylib/blob/1.7.0/lib/paths.bzl#L161
- https://github.com/bazelbuild/bazel-skylib/blob/1.7.0/lib/paths.bzl#L315