Import JavaInfo from @rules_java
Resolves the breakage from the previous commit, but now yields this
breakage under Bazel 9:

```txt
ERROR: Traceback (most recent call last):
  File "external/rules_magic+/magic/magic_library.bzl",
    line 9, column 33, in <toplevel>
      providers = [java_common.JavaToolchainInfo],
Error: 'struct' value has no field or method 'JavaToolchainInfo'
Available attributes: internal_DO_NOT_USE

WARNING: Target pattern parsing failed.

ERROR: Skipping '//...':
  error loading package under directory '':
  error loading package '':
  at external/rules_magic+/magic/magic.bzl:4:6:
  initialization of module 'magic/magic_library.bzl' failed
```

Bazel 7 and 8 builds using Bzlmod continue to pass. However, Bazel 6, 7,
and 8 builds now produce the following error in legacy `WORKSPACE` mode:

```txt
ERROR: Failed to load Starlark extension
  '@@rules_java//java/common:java_info.bzl'.

Cycle in the workspace file detected. This indicates that a repository
is used prior to being defined.

The following chain of repository dependencies lead to the missing definition.
 - @@rules_java

This could either mean you have to add the '@@rules_java' repository
with a statement like `http_archive` in your WORKSPACE file (note that
transitive dependencies are not added automatically), or move an
existing definition earlier in your WORKSPACE file.

ERROR: Error computing the main repository mapping:
  cycles detected during computation of main repo mapping
```

We'll fix this problem at the end of the `bazel-9` branch. The solution
is to keep legacy `WORKSPACE` setup macros in separate `.bzl` files from
rule and macro definitions.

---

Also stops suppressing the `native-java-info` warning in
`tools/lint.sh`, since this commit resolves the issue.