Define magic_binary as java_binary from rules_java
This would've been the proper way to define `magic_binary` from the
beginning, but would've broken legacy `WORKSPACE` builds with a
cyclic dependency error. We'll deal with this problem in the next
commit, though this dependency isn't a problem for Bzlmod builds.

This commit and the previous `JavaInfo` and `java_common` commits are
necessary because the Bazel 9 prereleases no longer autoloads symbols
from `rules_java`.

- https://bazel.build/reference/command-line-reference#common_options-flag--incompatible_autoload_externally
- bazelbuild/bazel#26906: Disable autoloads for Python, Java, Proto,
  Shell and Android
- https://github.com/bazelbuild/bazel/blob/8.4.2/src/main/java/com/google/devtools/build/lib/packages/semantics/FlagConstants.java#L31
- https://github.com/bazelbuild/bazel/blob/9.0.0-pre.20250921.2/src/main/java/com/google/devtools/build/lib/packages/semantics/FlagConstants.java#L29

This is a continuation of the Starlarkification of builtin rule sets
that allow the rule sets to evolve on a different schedule from Bazel.
Removing autoloads requires users to include explicitly whatever rules
they use from their original sources. This reduces Bazel's complexity,
avoids loading more rule sets than necessary in Bazel itself, and makes
dependencies more explicit right where they're used.

Setting `--incompatible_autoload_externally=+@rules_cc,java_binary`
would've had the same effect at this commit. However, this change,
combined with separating setup macros from rules in the next
commit, is a more correct, more robust fix.

This change now yields the following breakage related to
bazelbuild/bazel#26579:

```txt
ERROR: error loading package '@@bazel_tools//src/main/protobuf':
  Unable to find package for @@[unknown repo 'com_github_grpc_grpc'
    requested from @@bazel_tools]//bazel:cc_grpc_library.bzl:
  The repository '@@[unknown repo 'com_github_grpc_grpc'
    requested from @@bazel_tools]' could not be resolved:
  No repository visible as '@com_github_grpc_grpc'
    from repository '@@bazel_tools'.

ERROR: external/rules_magic+/src/com/frobozz/magic/BUILD:17:12:
  error loading package '@@bazel_tools//src/main/protobuf':
  Unable to find package for @@[unknown repo 'com_github_grpc_grpc'
    requested from @@bazel_tools]//bazel:cc_grpc_library.bzl:
  The repository '@@[unknown repo 'com_github_grpc_grpc'
    requested from @@bazel_tools]' could not be resolved:
  No repository visible as '@com_github_grpc_grpc'
    from repository '@@bazel_tools'. and referenced by
    '@@rules_magic+//src/com/frobozz/magic:EmitDigestsWorker'

ERROR: Analysis of target '//:hello' failed; build aborted: Analysis failed
```