Fix default @rules_magic_leaflet_repo target
Fixes the breakage in `@rules_magic_leaflet` from the previous commit by
using two mechanisms for generating a default target name in a
repository rule.

- Bazel 8.1.1 added `repository_ctx.original_name` to facilitate the
  generation of default repo target names.

- For earlier Bazels, the wrapper macro and `default_target_name`
  attribute pass through the original repo name for when
  `repository_ctx.original_name` isn't available.

Using both for now provides backwards and forward compatibility across
Bazel versions while avoiding the need for parsing the canonical repo
name format. The canonical repo name format has changed several times,
making this a very practical concern.

For more background, see:

- https://github.com/bazelbuild/bazel/issues/24467
- https://github.com/bazelbuild/bazel/pull/25121

And as for why we recommend using Bazel 8.1.1 or later, instead of 8.1.0
when `repository_ctx.original_name` first appeared:

- https://github.com/bazelbuild/bazel/issues/25286

---

However, the build now breaks with:

```txt
ERROR: external/rules_magic+/toolchains/BUILD:17:22:
  no such package '@@rules_magic+//external':
  BUILD file not found in directory 'external' of external repository
  @@rules_magic+. Add a BUILD file to a directory to mark it as a
  package. and referenced by
  '@@rules_magic+//toolchains:default_settings_toolchain_impl'

ERROR: Analysis of target '//:default-values' failed; build aborted:
  Analysis failed
```

This is because `native.bind` doesn't work under Bzlmod. We're not yet
hitting the error indicating that `native.bind` is no longer available,
but that the artifical `//external` package no longer exists.