Bump rules_java to 7.10.0
Resolves the `_allowlist_function_transition` error under Bazel 6.

However, it breaks `bootcamp_library` under Bazel 7, which currently
uses `@bazel_tools//tools/jdk:toolchain_jdk_17`, with the following
error:

```txt
$ USE_BAZEL_VERSION=7.6.1 bazel build //...

ERROR: external/rules_java_builtin/toolchains/BUILD:254:14:
  While resolving toolchains for target
  @@rules_java_builtin//toolchains:platformclasspath (096dcc8):
  No matching toolchains found for types
  @@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type.

To debug, rerun with --toolchain_resolution_debug='@@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type'
```

The next commit fixes this error by replacing it with
`@rules_java//toolchains:toolchain_jdk_17` instead.

---

This error happens because `rules_java` up to 7.9.1 contained the
following definition in `toolchains/default_java_toolchain.bzl`:

```python
_JAVA_BOOTSTRAP_RUNTIME_TOOLCHAIN_TYPE = Label("@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type")
```

and `rules_java` 7.10.0 changed it to:

```python
_JAVA_BOOTSTRAP_RUNTIME_TOOLCHAIN_TYPE = Label("//toolchains:bootstrap_runtime_toolchain_type")
```

- https://github.com/bazelbuild/rules_java/blob/7.9.1/toolchains/default_java_toolchain.bzl#L211
- https://github.com/bazelbuild/rules_java/blob/7.10.0/toolchains/default_java_toolchain.bzl#L211

This affects all toolchains defined using the `default_java_toolchain`
macro, which depend upon `//toolchains:platformclasspath`.
`@bazel_tools/tools/jdk:current_java_toolchain` isn't affected, because
it's defined using the `java_toolchain_alias` rule.

---

What follows comes largely from the "Bump to rules_java 7.9.0 for Bazel
7 compatibility" section of the following commit message, plus a few
corrections:

- https://github.com/bazel-contrib/rules_scala/commit/cd22d8896f209c37be8622f1dcc9770c2dc18f48

The `rules_java_builtin` repo is part of the legacy `WORKSPACE` prefix
that adds implicit dependencies:

- https://bazel.build/external/migration#builtin-default-deps

Bazel 7.0.0-pre.20230628.2 added `rules_java_builtin` in the following
change, mapping it to `@rules_java` within the scope of the
`@bazel_tools` repo:

- bazelbuild/bazel: Respect rules_java as the source of truth for java
  toolchains (second try)
  bazelbuild/bazel@3029a7db8a877e8a616b2ebe304573fae9ea9962

The following change tried to ensure `rules_java` 7.10.0 remained
compatible with earlier Bazel versions. However, it also changed
`@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type` to
`//toolchains:bootstrap_runtime_toolchain_type`:

- bazelbuild/rules_java: Make rules_java backwards compatible with Bazel
  6.3.0
  bazelbuild/rules_java@30ecf3ff6ee8f30b4df505d9d3bde5bb1c25690b

So when using Bazel 7 and `rules_java` 7.10.0 together under the legacy
`WORKSPACE` schema:

- Bazel creates `rules_java` 7.9.0 in the legacy `WORKSPACE` prefix as
  `@rules_java_builtin`.

- Bazel creates a repo mapping from `@rules_java` to
  `@rules_java_builtin` for `@bazel_tools`.

- Bazel then loads and invokes `rules_java_dependencies()` and
  `rules_java_toolchains()` from `@rules_java` 7.10.0 while evaluating
  the legacy `WORKSPACE` file. This creates toolchains of type
  `@rules_java//toolchains:bootstrap_runtime_toolchain_type` and
  registers them. (Under 7.9.0, the toolchain type would've been
  `@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type`.)

- A rule depends on `@bazel_tools//tools/jdk:toolchain_jdk_17` or
  another `@bazel_tools//tools/jdk` alias to `@rules_java//toolchains`.
  Because of the `@rules_java_builtin` repo mapping, the alias refers to
  a toolchain from `rules_java` 7.9.0, not 7.10.0.

- The `@rules_java_builtin` toolchain, if created with
  `default_java_toolchain()`, has a dependency on
  `//toolchains:platformclasspath`.

- `@rules_java_builtin//toolchains:platformclasspath` (from `rules_java`
  7.9.0) then fails during toolchain resolution. This is because it
  requires a `@bazel_tools//tools/jdk:bootstrap_runtime_toolchain_type`
  toolchain and doesn't find one.

This has broken other projects in the same way:

- bazelbuild/bazel: [Bazel CI] Downstream project broken by rules_java
  upgrade #23619
  bazelbuild/bazel#23619

These problems don't appear under Bzlmod, which never needed the
`@rules_java_builtin` mechanism. This is because legacy `WORKSPACE`
evaluation executes statements sequentially, while Bzlmod builds the
module dependency graph _before_ instantiating repositories (within
module extensions).

Bazel 8.0.0-pre.20240911.1 bumped `rules_java` in its
`workspace_deps.bzl` from 7.9.0 to 7.11.0. No Bazel 7 version contains
this change:

- bazelbuild/bazel: Update rules_java 7.11.1 / java_tools 13.8
  bazelbuild/bazel#23571
  bazelbuild/bazel@f92124acf3d0eb99d06570ddc380aca7ab354b90

Bazel 8 eventually removed `@rules_java_builtin` from the legacy
`WORKSPACE` prefix, and added `@rules_java` to the suffix.

- bazelbuild/bazel: Remove rules_java_builtin in WORKSPACE prefix
  bazelbuild/bazel@750669078e20f2c6ca7b9241e1c80564a1b8668e