Add rules_python 0.37.2 for Bazel 7
bazelbuild/bazel@78729c0fd6a854b710674fba5c337c4cba4d959c from Bazel 7
updates `@bazel_tools//src/main/protobuf` to depend on `@rules_python`.
This allows us to keep using rules_proto-5.3.0-21.7.

For details on why I chose rules_python 0.37.2, see:

- https://github.com/bazel-contrib/rules_scala/pull/1660#issuecomment-2529394863

Basically, it's the last version that doesn't pull in its own protobuf.
rules_python 0.38.0 pulls in protobuf v27 unconditionally.

Results in the following failure:

```txt
ERROR: external/remote_java_tools_darwin_arm64/BUILD:
  no such target
  '@@remote_java_tools_darwin_arm64//:turbine_direct_graal':
  target 'turbine_direct_graal' not declared in package ''
  defined by external/remote_java_tools_darwin_arm64/BUILD

ERROR: external/rules_java_builtin/toolchains/BUILD:163:14:
  no such target
  '@@remote_java_tools_darwin_arm64//:turbine_direct_graal':
  target 'turbine_direct_graal' not declared in package ''
  defined by external/remote_java_tools_darwin_arm64/BUILD
  and referenced by
  '@@rules_java_builtin//toolchains:turbine_direct_graal_darwin_arm64'

ERROR: Analysis of target '//:default-values' failed; build aborted:
  Analysis failed
```