Bump .bazelversion to 8.4.1
The Bazel 6 and 7 builds remain intact, but the Bazel 8 build fails
with:

```txt
ERROR: Traceback (most recent call last):
  File "external/rules_java/java/defs.bzl", line 46, column 28, in <toplevel>
    java_proto_library = native.java_proto_library
Error: no native function or rule 'java_proto_library'

Available attributes: action_listener, [...snip...], xcode_version

ERROR: Error computing the main repository mapping:
  at external/rules_java/java/repositories.bzl:20:6:
  at external/rules_java/toolchains/local_java_repository.bzl:17:6:
  initialization of module 'java/defs.bzl' failed
```

---

`//:example_test` now fails because the behavior of `$(location)` has changed
in Bazel 8 per bazelbuild/bazel#25198:

```txt
$ bazel test --test_output=all //...

[...snip...]
==================== Test output for //:example_test:
Executing: 'test.sh'
leaflet_path does not exist: external/io_frobozzco_rules_bootcamp_leaflet/leaflet.txt
================================================================================
```

This is because the value of `--legacy_external_runfiles` flipped from
`true` in Bazel 7 to `false` in Bazel 8. Building and testing using
`--nolegacy_external_runfiles` with Bazel 7 also fails, and using
`--legacy_external_runfiles` with Bazel 8 passes:

```txt
$ bazel test --test_output=all --legacy_external_runfiles //...

[...snip...]
==================== Test output for //:example_test:
Executing: 'test.sh'
Contents of "external/io_frobozzco_rules_bootcamp_leaflet/leaflet.txt":
---
In the interest of avoiding a potential copyright violation, please search for
"read leaflet" in the following document and read the contents from there:

https://web.mit.edu/marleigh/www/portfolio/Files/zork/transcript.html
---

================================================================================
```