Add default @rules_magic_leaflet_repo target patch
Converts `rules_magic` to a `git_repository` for now since one cannot
patch a `local_repository`.

The build now fails with:

```txt
ERROR: bootcamp/BUILD:23:14:
  While resolving toolchains for target //:default-values (7f8856b):
  No matching toolchains found for types:
  @@+_repo_rules+rules_magic//magic:toolchain_type

To debug, rerun with
  --toolchain_resolution_debug='@@+_repo_rules+rules_magic//magic:toolchain_type'
For more information on platforms or toolchains see
  https://bazel.build/concepts/platforms-intro.

ERROR: Analysis of target '//:default-values' failed; build aborted
```