Bump to protobuf v21.7, drop rules_proto
`rules_proto` 6.0.2 would work here, but we don't actually use
`@rules_proto` anywhere, so we just drop it. We'll eventually upgrade
`protobuf` to v28.0, at which point `rules_proto` isn't strictly
necessary anymore, since `protobuf` will contain `proto_library`, et.
al. See:

- https://github.com/bazelbuild/rules_proto/blob/7.1.0/README.md
- https://github.com/bazelbuild/rules_proto/blob/7.1.0/proto/defs.bzl

`protobuf` v21.7 works with Bazel 7 on Linux and Windows, but fails with
the following two errors on macOS. We'll fix the second error eventually
by upgrading to `protobuf` v28.0.

---

Building with Bazel 6 on macOS 26 Tahoe with Xcode 26 produces:

```txt
ERROR: external/zlib/BUILD.bazel:37:11:
  Compiling trees.c [for tool] failed: (Aborted): wrapped_clang failed:
  error executing command (from target @zlib//:zlib)
  external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1'
    -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety
    -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG
    '-DNS_BLOCK_ASSERTIONS=1' ... (remaining 34 arguments skipped)

dyld[78138]: missing LC_UUID load command in
  external/local_config_cc/wrapped_clang
dyld[78138]: missing LC_UUID load command
```

This is due to the `wrapped_clang` still included in the Bazel 6 version
of `@bazel_tools` containing an explicit `-no_uuid` linker flag. The
only way to fix this at the moment is to build a custom Bazel 6 binary
from source. (There may be a Bazel 6.6.0 release forthcoming with a fix
for this pending the outcome of bazelbuild/bazel#27463.)

For more details, and for instructions on building a new Bazel 6.5.0
binary for macOS 26, see bazelbuild/bazel#27026. We'll return to this in
the next commit message as well.

---

`protobuf` v21.7 uses Zlib 1.2.11, and versions v22.0 up until v28.0 use
Zlib 1.2.13. v28.0 upgrades to Zlib 1.3.1.

- https://github.com/protocolbuffers/protobuf/blob/v21.7/protobuf_deps.bzl#L53
- https://github.com/protocolbuffers/protobuf/blob/v22.0/protobuf_deps.bzl#L54-L55
- https://github.com/protocolbuffers/protobuf/blob/v27.5/protobuf_deps.bzl#L58-L59
- https://github.com/protocolbuffers/protobuf/blob/v28.0/protobuf_deps.bzl#L60-L61

Zlib versions before 1.3.1 cause the error below when building on macOS
with Xcode 16.4 and Clang 17. See:

- madler/zlib#895: Fix platform check for macOS
- madler/zlib@4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9:
  Remove fdopen #defines in zutil.h.
- llvm/llvm-project#74676:
  [clang][PP] Add extension to predefine target OS macros

```txt
$ bazel build //...

Starting local Bazel server and connecting to it...
INFO: Analyzed 2 targets (113 packages loaded, 2278 targets configured).

INFO: From Compiling adler32.c [for tool]:
In file included from external/zlib/adler32.c:8:
external/zlib/zutil.h:170:11: warning: 'OS_CODE' macro redefined [-Wmacro-redefined]
  170 | #  define OS_CODE 19
      |           ^
external/zlib/zutil.h:141:11: note: previous definition is here
  141 | #  define OS_CODE  7
      |           ^
1 warning generated.

[ ...snip OS_CODE warning from crc32.c:30... ]

ERROR: external/zlib/BUILD.bazel:37:11:
  Compiling zutil.c [for tool] failed: (Exit 1): cc_wrapper.sh failed:
  error executing CppCompile command (from target @@zlib//:zlib)
  external/local_config_cc/cc_wrapper.sh -U_FORTIFY_SOURCE
    -fstack-protector -Wall -Wthread-safety -Wself-assign
    -Wunused-but-set-parameter -Wno-free-nonheap-object
    -fcolor-diagnostics ... (remaining 33 arguments skipped)

ERROR: external/zlib/BUILD.bazel:37:11:
Compiling zutil.c [for tool] failed: (Exit 1): wrapped_clang failed:
error executing command (from target @zlib//:zlib)
external/local_config_cc/wrapped_clang '-D_FORTIFY_SOURCE=1'
-fstack-protector -fcolor-diagnostics -Wall -Wthread-safety
-Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG
'-DNS_BLOCK_ASSERTIONS=1' ... (remaining 35 arguments skipped)

[ ...snip OS_CODE warning from zutil.c:8... ]

In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/_stdio.h:318:7:
error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
external/zlib/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/17/include/__stddef_null.h:26:16:
note: expanded from macro 'NULL'
   26 | #define NULL ((void*)0)
      |                ^

[ ...snip two more error messages pointing into __stddef_null.h:26... ]

1 warning and 3 errors generated.

ERROR: external/com_frobozz_rules_magic/src/com/frobozz/magic/BUILD:3:12
  Building external/com_frobozz_rules_magic/src/com/frobozz/magic/EmitDigestsWorker.jar
  (1 source file) [for tool] failed: (Exit 1): cc_wrapper.sh failed:
  [ ...snip repeated CppCompile command error... ]
```