Use rules_magic_spells_* repos from toolchain ext
This solves the previous problem, as well as a related problem with the
tests using `spellbreaker_toolchain`.

Now the build breaks due to invoking `register_toolchains` in a module
extension:

```txt
ERROR: .../external/+_repo_rules+rules_magic/magic/magic.bzl:63:31:
  Traceback (most recent call last):
  File "bootcamp/extensions/rules_magic_toolchains.bzl",
    line 20, column 27, in _magic_toolchains_impl
      rules_magic_toolchains()
  File ".../external/+_repo_rules+rules_magic/magic/magic.bzl",
    line 63, column 31, in rules_magic_toolchains
      native.register_toolchains("//magic:all")

Error in register_toolchains: register_toolchains() can only be used
  while evaluating a WORKSPACE file

ERROR: Analysis of target '//:default-values' failed; build aborted:
  error evaluating module extension
  @@//extensions:rules_magic_toolchains.bzl%magic_toolchains
```