Bump rules_java to 7.9.1
Fixes the error described in the previous commit, but results in the
following failure:

```txt
ERROR: bootcamp/BUILD:23:14: in magic_library rule //:default-values:

Traceback (most recent call last):
  File "external/com_frobozz_rules_magic/magic/magic_library.bzl",
    line 66, column 28, in _magic_library_impl
      java_common.compile(
  File "/virtual_builtins_bzl/common/java/java_common.bzl",
    line 68, column 19, in _compile
  File "/virtual_builtins_bzl/common/java/java_common_internal_for_builtins.bzl",
    line 195, column 63, in compile

Error in create_header_compilation_action:
  Rule 'magic_library' in 'bootcamp/BUILD:23:14' must declare
  '@@bazel_tools//tools/jdk:toolchain_type' toolchain
  in order to use java_common.
  See https://github.com/bazelbuild/bazel/issues/18970.

ERROR: bootcamp/BUILD:23:14:
  Analysis of target '//:default-values' failed
ERROR: Analysis of target '//:default-values' failed; build aborted
```

This merely explains that rules using `java_common` must now declare
`@bazel_tools//tools/jdk:toolchain_type` in their `toolchains`
attribute. The error message contains a helpful reference to
bazelbuild/bazel#18970. See also:

- bazelbuild/bazel@d0e29582a2e788e8acdaf53fe30ab7f7dc592df3

This change also introduces this new error under Bazel 6:

```txt
ERROR: external/rules_java/toolchains/java_toolchain_alias.bzl:83:34:
  Use of Starlark transition without allowlist attribute
  '_allowlist_function_transition'. See Starlark transitions
  documentation for details and usage:
  @rules_java//toolchains:java_toolchain_alias.bzl NORMAL

ERROR: bzlmod-bootcamp/bootcamp/BUILD:23:14:
  While resolving toolchains for target //:default-values:
  invalid registered toolchain '//toolchains:all':
  while parsing '//toolchains:all':
  error loading package '@rules_java//toolchains':
  initialization of module 'toolchains/java_toolchain_alias.bzl' failed
```

`rules_java` 7.5.0 removed the private `_allowlist_function_transition`
attribute from `java_runtime_version_alias`, which Bazel 6.5.0 still
requires:

- bazelbuild/rules_java@57a8330d95ae62bf18bb5f2a0d82acde197196f3
- https://github.com/bazelbuild/bazel/blob/6.5.0/src/main/java/com/google/devtools/build/lib/analysis/starlark/StarlarkRuleClassFunctions.java#L934-L936