Add `repo_mapping` to `rules_magic` repo rule
This is a first attempt to fix legacy `WORKSPACE` build breakages
related to target strings containing their own repository's name.

As we can see, using the `repo_mapping` attribute of `local_repository`
or `http_archive` can help:

- https://bazel.build/versions/8.4.0/rules/lib/repo/http#http_archive-repo_mapping
- https://bazel.build/versions/8.4.0/reference/be/workspace#local_repository.repo_mapping

However, as illustrated by the error below, `repo_mapping` at this level
doesn't fix generated repositories that contain hardcoded references to
the original repo name. Even if such repository rules or macro wrappers
provided access to a `repo_mapping` attribute, it still imposes a burden
on users. Plus, Bzlmod doesn't support `repo_mapping` in a module
extension context.

```txt
ERROR: bootcamp/BUILD:34:8:
  error loading package '@com_frobozz_rules_magic_leaflet//':
  Unable to find package for
  @com_frobozz_rules_magic//magic:private/magic_leaflet.bzl:
  The repository '@com_frobozz_rules_magic' could not be resolved:
  Repository '@com_frobozz_rules_magic' is not defined.
  and referenced by '//:expansions'

ERROR: Analysis of target '//:leaflet' failed; build aborted:
  Analysis failed
```