Add patch to replace bind() with repo reference
Fixes the problem from the previous commit, but the build now fails
with:

```txt
ERROR: no such package '@@[unknown repo 'rules_magic_spells_enchanter'
  requested from @@+_repo_rules+rules_magic]//':
  The repository '@@[unknown repo 'rules_magic_spells_enchanter'
  requested from @@+_repo_rules+rules_magic]' could not be resolved:
  No repository visible as '@rules_magic_spells_enchanter'
  from repository '@@+_repo_rules+rules_magic'

ERROR: external/+_repo_rules+rules_magic/toolchains/BUILD:17:22:
  no such package '@@[unknown repo 'rules_magic_spells_enchanter'
  requested from @@+_repo_rules+rules_magic]//':
  The repository '@@[unknown repo 'rules_magic_spells_enchanter'
  requested from @@+_repo_rules+rules_magic]' could not be resolved:
  No repository visible as '@rules_magic_spells_enchanter'
  from repository '@@+_repo_rules+rules_magic' and referenced by
  '@@+_repo_rules+rules_magic//toolchains:default_settings_toolchain_impl'

ERROR: Analysis of target '//:default-values' failed; build aborted:
  Analysis failed
```

This is because we need to bring the `rules_magic_spells_enchanter` repo
into scope from the `magic_toolchains` extension.