Fix `magic_toolchains` module extension
The `magic_toolchains` module extension now invokes
`setup_magic_spells_repositories()` directly, instead of
`rules_magic_toolchains()`. This avoids the error described in the
previous commit due to `rules_magic_toolchains()` calling
`native.register_toolchains()` in a module extension context. (Also note
that the `rules_magic/MODULE.bazel` file already invokes
`register_toolchains()`.)

Also note that the extension file loads from a private `rules_magic`
file to access the macro. This is far from ideal, potentially
complicating patch maintenance, which is already a bit of a burden.

The build now breaks with a similar error to that described in
"Enable Bzlmod, keep legacy WORKSPACE support":

```txt
ERROR: .../external/+magic_toolchains+rules_magic_spells_enchanter/BUILD:
  no such target
  '@@+magic_toolchains+rules_magic_spells_enchanter//:rules_magic_spells_enchanter':
  target 'rules_magic_spells_enchanter' not declared in package ''
  defined by .../external/+magic_toolchains+rules_magic_spells_enchanter/BUILD

ERROR: .../external/+_repo_rules+rules_magic/magic/BUILD:38:22:
  no such target
  '@@+magic_toolchains+rules_magic_spells_enchanter//:rules_magic_spells_enchanter':
  target 'rules_magic_spells_enchanter' not declared in package ''
  defined by .../external/+magic_toolchains+rules_magic_spells_enchanter/BUILD
  and referenced by
  '@@+_repo_rules+rules_magic//magic:default_settings_toolchain_impl'

ERROR: Analysis of target '//:default-values' failed; build aborted:
  Analysis failed
```