Bump to Bazel 7.6.1
Results in the following failure:

```txt
ERROR: bootcamp/BUILD:8:14:
  While resolving toolchains for target //:default-values (096dcc8):
  invalid registered toolchain
  '@remotejdk11_linux_aarch64_toolchain_config_repo//:bootstrap_runtime_toolchain':
  no such target
  '@@remotejdk11_linux_aarch64_toolchain_config_repo//:bootstrap_runtime_toolchain':
  target 'bootstrap_runtime_toolchain' not declared in package ''
  defined by external/remotejdk11_linux_aarch64_toolchain_config_repo/BUILD.bazel
ERROR: Analysis of target '//:default-values' failed; build aborted
```