Bump rules_java to 7.9.1
Results in the following failure:

```txt
ERROR: bootcamp/BUILD:8:14: in magic_library rule //:default-values:

Traceback (most recent call last):
  File "external/com_frobozz_rules_magic/magic/magic_library.bzl",
    line 44, column 28, in _magic_library_impl
      java_common.compile(
  File "/virtual_builtins_bzl/common/java/java_common.bzl",
    line 68, column 19, in _compile
  File "/virtual_builtins_bzl/common/java/java_common_internal_for_builtins.bzl",
    line 195, column 63, in compile

Error in create_header_compilation_action:
  Rule 'magic_library' in 'bootcamp/BUILD:8:14' must declare
  '@@bazel_tools//tools/jdk:toolchain_type' toolchain
  in order to use java_common.
  See https://github.com/bazelbuild/bazel/issues/18970.

ERROR: bootcamp/BUILD:8:14:
  Analysis of target '//:default-values' failed
ERROR: Analysis of target '//:default-values' failed; build aborted
```

Also introduces this new error under Bazel 6:

```txt
ERROR: external/rules_java/toolchains/java_toolchain_alias.bzl:83:34:
  Use of Starlark transition without allowlist attribute
  '_allowlist_function_transition'. See Starlark transitions
  documentation for details and usage:
  @rules_java//toolchains:java_toolchain_alias.bzl NORMAL

ERROR: bzlmod-bootcamp/bootcamp/BUILD:7:17:
  While resolving toolchains for target //:default-values:
  invalid registered toolchain '//toolchains:all':
  while parsing '//toolchains:all':
  error loading package '@rules_java//toolchains':
  initialization of module 'toolchains/java_toolchain_alias.bzl' failed
```