Import java_common from @rules_java
Resolves the breakage from the previous commit, but produces the
following errors due to Bazel 9 no longer autoloading the
`native.java_binary` definition.

```txt
ERROR: bootcamp/BUILD:27:13: //:EmitValues:
  no such attribute 'srcs' in 'java_binary' rule
ERROR: bootcamp/BUILD:27:13: //:EmitValues:
  no such attribute 'main_class' in 'java_binary' rule
ERROR: bootcamp/BUILD:27:13: //:EmitValues:
  no such attribute 'deps' in 'java_binary' rule
```

See the next commit message for more details.

---

Also stops suppressing the `native-java-common` warning in
`tools/lint.sh`, since this commit resolves the issue.