Bump to rules_java 8.5.0
Resolves the previous error under Bazel 8, but Bazel 8 now produces:

```txt
ERROR: external/com_google_protobuf/bazel/private/native.bzl:3:19:
  name 'ProtoInfo' is not defined (did you mean 'proto'?)

ERROR: Error computing the main repository mapping:
  at external/rules_java/java/repositories.bzl:20:6:
  at external/rules_java/toolchains/local_java_repository.bzl:17:6:
  at external/rules_java/java/toolchains/java_runtime.bzl:16:6:
  at external/compatibility_proxy/proxy.bzl:6:6:
  at external/rules_java/java/bazel/rules/bazel_java_test.bzl:20:6:
  at external/rules_java/java/bazel/rules/bazel_java_binary.bzl:26:6:
  at external/rules_java/java/common/rules/impl/java_binary_impl.bzl:17:6:
  at external/com_google_protobuf/bazel/common/proto_info.bzl:3:6:
compilation of module 'bazel/private/native.bzl' failed
```

This is because Bazel 8.0.0 removed the builtin `ProtoInfo` provider:

- bazelbuild/bazel#24291: Remove proto providers
  bazelbuild/bazel@25518e0a08821cace4969ea926146989136aa2dd

That pull request cherry-picks the following from the Bazel 9 rolling
releases:

- bazelbuild/bazel#: Stop exporting proto_common and ProtoInfo
  bazelbuild/bazel@09ca1f3018db45c716817050aee18a13563b6b4b

- bazelbuild/bazel#: Remove ProtoInfo from Bazel
  bazelbuild/bazel@a1af43cd4ec8731b39a98401b33f1f27aa0904dd

Note that the Bazel 9 rolling releases also contain:

- bazelbuild/bazel#: Remove Starlark ProtoInfo from Bazel
  bazelbuild/bazel@fd43a3fd901af57bf0f6a2ceb621ff9d95a60431

---

Bazel 6.5.0 and 7.7.0 now produce the following error (Bazel 7 fails on
@@com_frobozz_rules_magic//src/com/frobozz/magic:EmitDigestsWorker):

```txt
ERROR: bzlmod-bootcamp/bootcamp/BUILD:23:14:
  While resolving toolchains for target //:default-values:
  invalid registered toolchain '//toolchains:all':
  while parsing '//toolchains:all':
  error loading package '@rules_java//toolchains':
  cannot load '@rules_cc//cc:cc_library.bzl': no such file
```

This is because this file doesn't exist until `rules_cc` 0.0.10, and
these builds are using `rules_cc` 0.0.9.

---

Normally we're lucky and can tell the version of a repo in the
`output_base` by reading its `MODULE.bazel` file. For example, after
building with either Bazel 6.5.0 or 7.7.0, we can run:

```sh
vim "$(bazel info output_base)/external/rules_cc/MODULE.bazel"
```

(Note that building with 8.4.2 actually deletes the external `rules_cc`
repository, so this command will open a blank editor in that case.)

However, in the case of `rules_cc` 0.0.9, its `MODULE.bazel` will show
`version = "0.0.4"`:

- https://github.com/bazelbuild/rules_cc/blob/0.0.9/MODULE.bazel#L3

A more reliable method, when running with at least Bazel 7, comes from
the Bzlmod Migration Guide:

- https://bazel.build/external/migration#inspect_external_dependency_with_workspace_resolved_file

In this case, we can run:

```sh
bazel clean --expunge_async
USE_BAZEL_VERSION=7.7.0 bazel build --nobuild \
  --experimental_repository_resolved_file=resolved.bzl //...
```

Then we can examine the `resolved.bzl` file for the repo in question and
find its exact version and what instantiated it. We can even download
the archive, and inspect it for ourselves.