Disable autoloads for @cc_compatibility_proxy
Fixes the Bazel 8 legacy `WORKSPACE` breakage for `rules_cc` >= 2.12 by
setting `--repositories_without_autoloads=cc_compatibility_proxy` in
`.bazelrc`.

This may not be necessary if a future Bazel 8 release adds
`cc_compatibility_proxy` to `PREDECLARED_REPOS_DISALLOWING_AUTOLOADS`:

- https://github.com/bazelbuild/bazel/blob/8.4.2/src/main/java/com/google/devtools/build/lib/packages/AutoloadSymbols.java#L679-L698

The other remedy suggested by the error message in the previous commit,
disabling autoloads by setting '--incompatible_autoload_externally=',
breaks `protobuf` v31.1:

```txt
ERROR: .../external/com_google_protobuf/java/core/BUILD.bazel:169:21:
  @@com_google_protobuf//java/core:lite_mvn-lib:
  no such attribute 'javacopts' in 'java_library' rule
ERROR: .../external/com_google_protobuf/java/core/BUILD.bazel:169:21:
  @@com_google_protobuf//java/core:lite_mvn-lib:
  no such attribute 'resources' in 'java_library' rule
  (did you mean 'features'?)
ERROR: .../external/com_google_protobuf/java/core/BUILD.bazel:169:21:
  @@com_google_protobuf//java/core:lite_mvn-lib:
  no such attribute 'runtime_deps' in 'java_library' rule
ERROR: .../external/com_google_protobuf/java/core/BUILD.bazel:287:21:
  @@com_google_protobuf//java/core:core_mvn-lib:
  no such attribute 'javacopts' in 'java_library' rule
ERROR: .../external/com_google_protobuf/java/core/BUILD.bazel:287:21:
  @@com_google_protobuf//java/core:core_mvn-lib:
  no such attribute 'resources' in 'java_library' rule
  (did you mean 'features'?)
ERROR: .../external/com_google_protobuf/java/core/BUILD.bazel:287:21:
  @@com_google_protobuf//java/core:core_mvn-lib:
  no such attribute 'runtime_deps' in 'java_library' rule

ERROR: .../external/com_google_protobuf/BUILD.bazel:493:6:
  Target '@@com_google_protobuf//java/core:toolchain' contains an error
  and its package is in error and referenced by
  '@@com_google_protobuf//:java_toolchain'
```