Bump to Bazel 7.7.0
This Bazel version bump results in the following failure:

```txt
ERROR: bootcamp/BUILD:23:14:
  While resolving toolchains for target //:default-values (096dcc8):
  invalid registered toolchain
  '@remotejdk11_linux_aarch64_toolchain_config_repo//:bootstrap_runtime_toolchain':
  no such target
  '@@remotejdk11_linux_aarch64_toolchain_config_repo//:bootstrap_runtime_toolchain':
  target 'bootstrap_runtime_toolchain' not declared in package ''
  defined by external/remotejdk11_linux_aarch64_toolchain_config_repo/BUILD.bazel
ERROR: Analysis of target '//:default-values' failed; build aborted
```

This is due to a classic legacy `WORKSPACE` repo ordering issue that
Bzlmod prevents from ever happening.

- Bazel 7.7.0 includes the `rules_java` 7.6.5 archive and instantiates
  it as `rules_java_builtin` in the legacy `WORKSPACE` prefix. This
  prefix injects default dependencies required by Bazel's built in
  repos.

  https://bazel.build/external/migration#builtin-default-deps
  https://github.com/bazelbuild/bazel/blob/7.7.0/src/main/java/com/google/devtools/build/lib/bazel/rules/JavaRules.java#L94-L96
  https://github.com/bazelbuild/bazel/blob/7.7.0/src/main/java/com/google/devtools/build/lib/bazel/rules/java/rules_java_builtin.WORKSPACE

- The legacy `bootcamp/WORKSPACE` file invokes `rules_magic_deps` after
  the legacy `WORKSPACE` prefix finishes, which instantiates
  `rules_java` 5.4.0.

- `rules_java_dependencies` then instantiates remote JDK toolchain repos
  using its version of `remote_java_repository`. The repos generated by
  this version do _not_ contain a `bootstrap_runtime_toolchain` target.

- The legacy `WORKSPACE` suffix invokes `rules_java_dependencies` from
  `rules_java_builtins`, which is `rules_java` 7.6.5.

  https://github.com/bazelbuild/bazel/blob/7.7.0/src/main/java/com/google/devtools/build/lib/bazel/rules/JavaRules.java#L97-L98
  https://github.com/bazelbuild/bazel/blob/7.7.0/src/main/java/com/google/devtools/build/lib/bazel/rules/java/jdk.WORKSPACE.tmpl#L43-L45

- The remote JDK toolchain repos produced by `remote_java_repository`
  from this version _would_ contain a `bootstrap_runtime_toolchain`
  target. However, the macros instantiating remote JDK toolchain repos
  wrap `remote_java_repository` in a `maybe`. As a result, nothing
  happens, because the repos already exist.

  https://github.com/bazelbuild/rules_java/blob/7.6.5/java/repositories.bzl#L331-L341

- It then invokes the 7.6.5 version of `rules_java_toolchains`, which
  registers `bootstrap_runtime_toolchain` targets from the config repos.
  Because `rules_java` 5.4.0 generated these existing toolchain config
  repos, they do not actually contain `bootstrap_runtime_toolchain`
  targets.

  https://github.com/bazelbuild/rules_java/blob/7.6.5/java/repositories.bzl#L391

- When Bazel begins resolving toolchains, it notices that one of the
  `bootstrap_runtime_toolchain` targets doesn't actually exist, breaking
  the build.

The fine grained details are below.

---

`rules_java` 6.5.0 introduced the `bootstrap_runtime_toolchain` target
into repos generated by `toolchains/remote_java_repository.bzl`.

- bazelbuild/rules_java#114: Obtain bootstrap class path from dedicated
  runtime toolchain type
  bazelbuild/rules_java@ea0bd911702b75ea940886d278731092f8e227c3

We can see this target does not exist in `rules_java` 5.4.0, and does
exist in 7.6.5:

- https://github.com/bazelbuild/rules_java/blob/5.4.0/toolchains/remote_java_repository.bzl
- https://github.com/bazelbuild/rules_java/blob/7.6.5/toolchains/remote_java_repository.bzl

Bazel 6 compiles itself in the legacy `WORKSPACE` mode, which invokes
the `distdir_tar` repo rule to create the `@additional_distfiles` repo.
This repo contains the archives from the `DIST_DEPS` dict from
`//:distdir_deps.bzl` that have `additional_distfiles` in their
`used_in` attribute. This includes `rules_java` 5.5.1. (The `rules_java`
5.4.0 specified in `@rules_magic//magic:deps.bzl`, which eventually
clobbers the builtin version, remains compatible with Bazel 6.)

- https://github.com/bazelbuild/bazel/blob/6.5.0/.bazelrc
- https://github.com/bazelbuild/bazel/blob/6.5.0/WORKSPACE#L123-L132
- https://github.com/bazelbuild/bazel/blob/6.5.0/distdir.bzl
- https://github.com/bazelbuild/bazel/blob/6.5.0/distdir_deps.bzl#L64-L75

The `//:bazel-distfile` target used to build the Bazel 6 source archive
includes these archives within the `derived/distdir` directory. (This is
the directory from the `dirname` attribute of `distdir_tar`.)
`scripts/bootstrap/bootstrap.sh`, sourced by `compile.sh`, then sets
`--distdir=derived/distdir` in `_BAZEL_ARGS`.

- https://github.com/bazelbuild/bazel/blob/6.5.0/BUILD#L175-L190
- https://github.com/bazelbuild/bazel/blob/6.5.0/scripts/bootstrap/bootstrap.sh#L43
- https://github.com/bazelbuild/bazel/blob/6.5.0/compile.sh#L59
- https://bazel.build/reference/command-line-reference#common_options-flag--distdir
- https://github.com/bazelbuild/bazel/releases/download/6.5.0/bazel-6.5.0-dist.zip
- https://bazel.build/versions/6.5.0/install/compile-source

Bazel 7 introduced the `rules_java_builtin` repo into its legacy
`WORKSPACE` prefix, which it originally defines as `rules_java` 6.1.0.
It also embedded the `rules_java` archive into `//:bazel-distfile`.

- bazelbuild/bazel: Respect rules_java as the source of truth for java
  toolchains (second try)
  bazelbuild/bazel@3029a7db8a877e8a616b2ebe304573fae9ea9962
  https://github.com/bazelbuild/bazel/blob/3029a7db8a877e8a616b2ebe304573fae9ea9962/MODULE.bazel#L19
  https://github.com/bazelbuild/bazel/blob/3029a7db8a877e8a616b2ebe304573fae9ea9962/distdir_deps.bzl#L65-L72

- bazelbuild/bazel: Embed rules_java in bazel
  bazelbuild/bazel@30b21303b0fd65c70285ea0832db18f78ad9fd0f
  https://github.com/bazelbuild/bazel/blob/30b21303b0fd65c70285ea0832db18f78ad9fd0f/BUILD#L167-L172
  https://github.com/bazelbuild/bazel/blob/30b21303b0fd65c70285ea0832db18f78ad9fd0f/BUILD#L196
  https://github.com/bazelbuild/bazel/blob/30b21303b0fd65c70285ea0832db18f78ad9fd0f/src/main/java/com/google/devtools/build/lib/bazel/rules/java/rules_java_builtin.WORKSPACE
  https://github.com/bazelbuild/bazel/blob/30b21303b0fd65c70285ea0832db18f78ad9fd0f/src/package-bazel.sh

However, the official Bazel 7.0.0 release compiles in Bzlmod mode.

- bazelbuild/bazel: Enable Bzlmod for Bazel
  bazelbuild/bazel@136dae1fdc8ef529693090cd00c2d46daeca23d7
  https://github.com/bazelbuild/bazel/blob/7.0.0/.bazelrc#L44-L49

Instead of `--distdir=derived/distdir`, `scripts/bootstrap/bootstrap.sh`
now sets `--repository_cache=derived/repository_cache` in `_BAZEL_ARGS`.

- https://github.com/bazelbuild/bazel/blob/7.0.0/scripts/bootstrap/bootstrap.sh#L40
- https://bazel.build/reference/command-line-reference#common_options-flag--repository_cache
- https://github.com/bazelbuild/bazel/releases/download/7.0.0/bazel-7.0.0-dist.zip
- https://bazel.build/versions/7.0.0/install/compile-source

`derived/repository_cache` comes from the `bazel_build_deps` module
extension from `//:extensions.bzl`. Specifically, from the
`@bootstrap_repo_cache` repo instantiated by the `repo_cache_tar` repo
rule based on `DIST_ARCHIVE_REPOS` from `//:repositories.bzl`.
`//:bazel-distfile` now depends on `@bootstrap_repo_cache`.

- https://github.com/bazelbuild/bazel/blob/7.0.0/MODULE.bazel#L258-L262
- https://github.com/bazelbuild/bazel/blob/7.0.0/extensions.bzl#L32
- https://github.com/bazelbuild/bazel/blob/7.0.0/distdir.bzl#L80
- https://github.com/bazelbuild/bazel/blob/7.0.0/repositories.bzl#L38
- https://github.com/bazelbuild/bazel/blob/7.0.0/BUILD#L214

Also, by this point, it sets `rules_java` to 7.1.0, which gets baked in
as `rules_java_builtin`:

- https://github.com/bazelbuild/bazel/blob/7.0.0/MODULE.bazel#L26

By Bazel 7.7.0, this becomes `rules_java` 7.6.5, revealed by
`$(bazel info output_base)/external/rules_java_builtin/MODULE.bazel`.

- https://github.com/bazelbuild/bazel/blob/7.7.0/WORKSPACE
- https://github.com/bazelbuild/bazel/blob/7.7.0/MODULE.bazel#L26