Enable Bzlmod, keep legacy WORKSPACE support
Nothing has changed in the legacy `WORKSPACE` setup, so it will continue
to work with Bazel 6, 7, and 8. Added `.bazellegacyrc` and updated
`run_tests.sh` and `tools/bazel` to support running in legacy
`WORKSPACE` mode easily.

Bzlmod currently fails under Bazel 7 and 8 with:

```txt
ERROR: external/rules_magic++magic_leaflet+rules_magic_leaflet/BUILD:
  no such target
  '@@rules_magic++magic_leaflet+rules_magic_leaflet//:rules_magic_leaflet':
  target 'rules_magic_leaflet' not declared in package '' defined by
  external/rules_magic++magic_leaflet+rules_magic_leaflet/BUILD

ERROR: bootcamp/BUILD:43:11: no such target
  '@@rules_magic++magic_leaflet+rules_magic_leaflet//:rules_magic_leaflet':
  target 'rules_magic_leaflet' not declared in package '' defined by
  external/rules_magic++magic_leaflet+rules_magic_leaflet/BUILD
  and referenced by '//:example_test'

ERROR: Analysis of target '//:example_test' failed; build aborted:
  Analysis failed
```

This is because of the new canonical repo name schema, and the fact that
values from `repository_ctx.name` now use this new schema. Since `@repo`
is a valid shortened target name for `@repo//:repo`, many repo rules use
`repository_ctx.name` to name this default target. So the default target
name above is now `rules_magic++magic_leaflet+rules_magic_leaflet`, not
`rules_magic_leaflet`.

---

`bootcamp/MODULE.bazel` sets `rules_java` to 8.14.0 to eliminate the
following warning when building with Bazel 8:

```txt
WARNING: For repository 'rules_java', the root module requires module
  version rules_java@8.6.0, but got rules_java@8.14.0 in the resolved
  dependency graph. Please update the version in your MODULE.bazel or
  set --check_direct_dependencies=off
```

---

Bazel 6.5.0 Bzlmod builds will not work, because `protobuf` v29.0 uses
`rules_jvm_external` 6.3. That dependency needs `use_repo_rule`, which
6.5.0 doesn't support.

```txt
$ USE_BAZEL_VERSION=6.5.0 bazel build //...

ERROR: https://bcr.bazel.build/modules/rules_jvm_external/6.3/MODULE.bazel:101:13:
  name 'use_repo_rule' is not defined

ERROR: Error computing the main repository mapping:
  in module dependency chain
  <root> -> rules_magic@_ -> protobuf@29.0 -> rules_jvm_external@6.3:
  error executing MODULE.bazel file for rules_jvm_external@6.3
```