Update Bazel to 9.0.0-pre.20251029.2
This the latest `rolling` release as of 2025-11-02. Also bumps
dependency versions to avoid the warnings below:

- `bazel_features`: 1.19.0 => 1.30.0 (for `rules_java` 8.16.1)
- `protobuf`: 29.0 => 29.5 (legacy WORKSPACE), 32.1 (Bzlmod)
- `rules_cc`: 0.1.1 => 0.2.11
- `rules_java`: 8.14.0 => 8.16.1
- `rules_python`: 1.0.0 => 1.4.1

```txt
WARNING: For repository 'protobuf', the root module requires module
  version protobuf@29.0, but got protobuf@32.1 in the resolved
  dependency graph. Please update the version in your MODULE.bazel or
  set --check_direct_dependencies=off

WARNING: For repository 'rules_cc', the root module requires module version
  rules_cc@0.0.14, but got rules_cc@0.2.11 in the resolved dependency
  graph.  Please update the version in your MODULE.bazel or set
  --check_direct_dependencies=off

WARNING: For repository 'rules_java', the root module requires module
  version rules_java@8.14.0, but got rules_java@8.16.1 in the resolved
  dependency graph. Please update the version in your MODULE.bazel or
  set --check_direct_dependencies=off

WARNING: For repository 'rules_python', the root module requires module
  version rules_python@1.0.0, but got rules_python@1.4.1 in the resolved
  dependency graph.  Please update the version in your MODULE.bazel or
  set --check_direct_dependencies=off
```

Makes corresponding updates to `rules_magic/deps.bzl` dependency
versions and the legacy `WORKSPACE` files. See the new comments from
those changes for details.

---

Some more background on the introduction of `bazel_skylib` in
`rules_magic_deps`:

Per the `rules_java` 8.15.2 release notes, we must invoke
`bazel_feature_deps` explicitly before `protobuf_deps` and
`rules_java_toolchains`. Per 8.16.0, we now must invoke it before
`rules_java_dependencies`:

- https://github.com/bazelbuild/rules_java/releases/tag/8.15.2
- https://github.com/bazelbuild/rules_java/releases/tag/8.16.0

`bazel_features_deps` instantiates `bazel_skylib` 1.6.1 by default.
`protobuf` >= v29 needs `bazel_skylib` >= 1.7.0, which contains
`paths.is_normalize`. Because `bazel_features_deps` comes before
`rules_java_dependencies` and `protobuf_deps`, we now instantiate
`bazel_skylib` v1.7.0 in `rules_magic_deps`.

Yet another example illustrating why Bzlmod must replace the legacy
`WORKSPACE` model.

---

With all that sorted out, the Bzlmod build for the new Bazel version
currently breaks with:

```txt
ERROR: external/rules_magic+/magic/magic_library.bzl:78:17:
  name 'JavaInfo' is not defined

WARNING: Target pattern parsing failed.

ERROR: Skipping '//...': error loading package under directory '':
  error loading package '':
  at external/rules_magic+/magic/magic.bzl:19:6:
  compilation of module 'magic/magic_library.bzl' failed
```

---

The `MODULE.bazel.lock` files are now much smaller than the previous
commit after re-running `bazel mod deps --lockfile_mode=refresh`. This
is likely due to a combination of an improved Bazel lockfile
implementation, and module extensions from newer dependency versions
marking themselves as reproducible.

- https://bazel.build/versions/8.4.0/external/extension#specify_reproducibility

---

`protobuf` v32.0 requires a version of `abseil-cpp` that requires at
least C++17. The default for Bazel 7 is still C++14, so Bazel 7 builds
produce the following error by default:

```txt
ERROR: external/abseil-cpp+/absl/time/internal/cctz/BUILD.bazel:40:11:
  Compiling absl/time/internal/cctz/src/time_zone_posix.cc [for tool]
  failed: (Exit 1): cc_wrapper.sh failed: error executing CppCompile
  command (from target @@abseil-cpp+//absl/time/internal/cctz:time_zone)
  external/bazel_tools+cc_configure_extension+local_config_cc/cc_wrapper.sh
  -U_FORTIFY_SOURCE -fstack-protector -Wall -Wthread-safety
  -Wself-assign -Wunused-but-set-parameter -Wno-free-nonheap-object ...
  (remaining 82 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain
the sandbox build root for debugging
In file included from external/abseil-cpp+/absl/time/internal/cctz/src/time_zone_posix.cc:15:
In file included from external/abseil-cpp+/absl/time/internal/cctz/src/time_zone_posix.h:58:
In file included from external/abseil-cpp+/absl/base/config.h:92:
external/abseil-cpp+/absl/base/policy_checks.h:81:2: error:
  "C++ versions less than C++17 are not supported."
   81 | #error "C++ versions less than C++17 are not supported."
      |  ^
1 error generated.
```

The update to `tools/bazel` sets C++17 compiler flags for Bazel 7,
enabling it to build successfully with `protobuf` v32.