Replace @bazel_tools with @bazel_worker_api
Replaces `@bazel_tools//src/main/protobuf:worker_protocol_java_proto`
with a dependency on `@bazel_worker_api//:worker_protocol_proto`. This
fixes the breakage from the previous commit, and works with all bazels,
including the `last_green` Bazel.

For the reason behind this, see:

- https://github.com/bazelbuild/bazel/issues/26579#issuecomment-3120862995

Notice the `strip_prefix` trick to make the repo available under legacy
`WORKSPACE` builds.

Legacy `WORKSPACE` builds still fail with a message similar to the one
from "Import JavaInfo from @rules_java". The only difference is that
loading `@rules_java//java:defs.bzl` in `//magic:magic.bzl` produces the
breakage first.

```txt
ERROR: Failed to load Starlark extension '@@rules_java//java:defs.bzl'.

Cycle in the workspace file detected. This indicates that a repository
is used prior to being defined.

The following chain of repository dependencies lead to the missing
definition.
 - @@rules_java

This could either mean you have to add the '@@rules_java' repository
with a statement like `http_archive` in your WORKSPACE file (note that
transitive dependencies are not added automatically), or move an
existing definition earlier in your WORKSPACE file.

ERROR: Error computing the main repository mapping:
  cycles detected during computation of main repo mapping
```

---

Now that the `@bazel_tools//src/main/protobuf` dependency no longer
exists, this also bumps `protobuf` to v31.1 in `rules_magic/deps.bzl`.
This is the maximum version so long as we support Bazel 6, since
`protobuf` v32 explicitly breaks Bazel 6 legacy `WORKSPACE` builds:

- https://github.com/protocolbuffers/protobuf/blob/v32.0/bazel/proto_library.bzl#L14-L16

---

`rules_magic/src/com/frobozz/magic/BUILD` needs to continue loading from
`com_google_protobuf` so legacy `WORKSPACE` builds don't break under
Bazel 8. This is why the `protobuf` Bazel module now requires `repo_name
= "com_google_protobuf"`. Without this, legacy `WORKSPACE` builds will
silently use two different `protobuf` versions that will yield
incompatibility errors.

To reproduce the following errors, first reach the end of the `bazel-9`
branch to resolve the `Cycle in the workspace file` error. Then change
`com_google_protobuf` to `protobuf` in `rules_magic/magic/deps.bzl` and
`rules_magic/src/com/frobozz/magic/BUILD`. Bazel 6 and 7 builds will
complete, but Bazel 8 builds will fail.

Bazel 8 will first break with:

```txt
ERROR: external/rules_magic/src/com/frobozz/magic/BUILD:13:19:
  in deps attribute of java_proto_library rule
  @@rules_magic//src/com/frobozz/magic:worker_protocol_java_proto:
  '@@bazel_worker_api//:worker_protocol_proto' does not have mandatory
  providers: 'ProtoInfo'.

  Since this rule was created by the macro 'java_proto_library', the
  error might have been caused by the macro implementation

ERROR: external/rules_magic/src/com/frobozz/magic/BUILD:13:19:
  Analysis of target
  '@@rules_magic//src/com/frobozz/magic:worker_protocol_java_proto'
  (config: d881af7) failed

ERROR: Analysis of target '//:hello' failed; build aborted:
  Analysis failed
```

After adding `repo_mapping = {"@com_google_protobuf": "@protobuf"}` to
the `http_archive` for `bazel_worker_api`, it breaks with:

```txt
ERROR: external/bazel_worker_api/BUILD.bazel:5:14: in
  @@protobuf//bazel/private:bazel_java_proto_library_rule.bzl%bazel_java_proto_aspect
  aspect on proto_library rule
  @@bazel_worker_api//:worker_protocol_proto:

Traceback (most recent call last):
  File "external/protobuf/bazel/private/bazel_java_proto_library_rule.bzl",
    line 40, column 53, in _bazel_java_proto_aspect_impl
      proto_toolchain_info = toolchains.find_toolchain(ctx, "_aspect_java_proto_toolchain", _JAVA_PROTO_TOOLCHAIN)
  File "external/protobuf/bazel/private/toolchain_helpers.bzl",
    line 29, column 46, in _find_toolchain
      return getattr(ctx.attr, legacy_attr)[ProtoLangToolchainInfo]

Error: <target @@com_google_protobuf//java/core:toolchain>
  (rule 'proto_lang_toolchain') doesn't contain declared provider
  'ProtoLangToolchainInfo'

ERROR: Analysis of target '@@bazel_worker_api//:worker_protocol_proto'
  (config: d881af7) failed

ERROR: Analysis of target '//:hello' failed; build aborted:
  Analysis failed
```

The `@@com_google_protobuf//java/core:toolchain` target is an alias from
`@@bazel_tools//tools/proto:java_toolchain` in Bazel 6, 7, and 8.
(Patching `_find_toolchain` in `protobuf` v31.1 to `print` the
`legacy_attr` value revealed this.)

- https://github.com/bazelbuild/bazel/blob/6.5.0/tools/proto/BUILD#L20-L23
- https://github.com/bazelbuild/bazel/blob/7.6.2/tools/proto/BUILD#L20-L23
- https://github.com/bazelbuild/bazel/blob/8.4.2/tools/proto/BUILD#L23-L26

Running `./repo-info.py -v` shows that `com_google_protobuf` comes from
`rules_java_dependencies`, and `protobuf` from our `deps.bzl` file.

```txt
$ USE_BAZEL_VERSION=8.4.2 bazel clean --expunge_async
$ USE_BAZEL_VERSION=8.4.2 bazel build --nobuild \
  --noenable_bzlmod --enable_workspace \
  --experimental_repository_resolved_file=out.bzl \
  @rules_magic//src/com/frobozz/magic:worker_protocol_java_proto

$ ./repo-info.py out.bzl {com_google_,}protobuf
com_google_protobuf: https://github.com/.../protobuf-29.0-rc2.tar.gz
protobuf: https://github.com/protocolbuffers/protobuf/.../v31.1.tar.gz
```

`@bazel_worker_api` v0.0.6 imports `proto_library` from
`com_google_protobuf`. The `proto_library` macro in both `protobuf`
v29.0-rc2 and v31.1 will use `native.java_proto_library` if present, or
its Starlarkified implementation otherwise.

- https://github.com/bazelbuild/bazel-worker-api/blob/v0.0.6/proto/BUILD.bazel
- https://github.com/protocolbuffers/protobuf/blob/v29.0-rc2/bazel/java_proto_library.bzl
- https://github.com/protocolbuffers/protobuf/blob/v31.1/bazel/java_proto_library.bzl

Patching `protobuf` v31.1 and running `bazel build --nobuild ...`
revealed that Bazel 7 uses the native version, and Bazel 8 uses the
Starlark version.

```diff
diff --git i/bazel/java_proto_library.bzl w/bazel/java_proto_library.bzl
index 31746e980..aaf74ffb5 100644
--- i/bazel/java_proto_library.bzl
+++ w/bazel/java_proto_library.bzl
@@ -11,6 +11,8 @@ load("//bazel/private:bazel_java_proto_library_rule.bzl", _java_proto_library =
 def java_proto_library(**kwattrs):
     # Only use Starlark rules when they are removed from Bazel
     if not hasattr(native, "java_proto_library"):
+        print("STARLARK JAVA_PROTO_LIBRARY")
         _java_proto_library(**kwattrs)
     else:
+        print("NATIVE JAVA_PROTO_LIBRARY")
         native.java_proto_library(**kwattrs)  # buildifier: disable=native-java-proto
```

The following commit from Bazel 8.0.0-pre.20240128.3 removed
`native.java_proto_library`:

- Generate java_proto_library documentation from bzl
  bazelbuild/bazel@862b94ff78810289b869fe99545bca25dcfbee6b

So when both versions of protobuf in the build use `native.java_proto_library`,
as with Bazel 6 and 7, everything works. When they use their Starlarkified
versions in Bazel 8, their provider types don't match, despite being
structurally identical, since they're loaded from different files.

For another data point, the following Bazel change relieves the first
error seen above (before applying the `repo_mapping`):

- bazelbuild/bazel#24283: Use `java_proto_library` from `@proto` to match the
  `proto_library` from `@proto`, otherwise the `ProtoInfo` providers don't match
  https://github.com/bazelbuild/bazel/commit/3a790821e74ace4f5975601c82781c413c3d37f0
  https://github.com/bazelbuild/bazel/commit/3edda22913d1d42fb112c014fbb68f30993f5c18